services:
  uxlab-shell:
    build:
      context: .
      dockerfile: Dockerfile
      target: shell
    ports:
      - "4200:80"
    networks:
      - uxlab-network

  uxlab-features:
    build:
      context: .
      dockerfile: Dockerfile
      target: features
    ports:
      - "4202:80"
    networks:
      - uxlab-network

networks:
  uxlab-network:
    driver: bridge
