server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Global CORS headers (allow host at 4200 to fetch remote assets)
    # add_header Access-Control-Allow-Origin "*" always;
    # add_header Access-Control-Allow-Methods "GET, HEAD, POST, OPTIONS" always;
    # add_header Access-Control-Allow-Headers "Origin, Content-Type, Accept, Authorization" always;
    # add_header Cross-Origin-Resource-Policy "cross-origin" always;

    # Handle SPA routing
    location / {
        try_files $uri $uri/ /index.html;
    }
}
